<?php echo $this->doctype() . PHP_EOL ;  ?> 
<html lang="fr">
    <head>
        <!-- Meta -->
        <?php $this->headTitle()->setSeparator(' - '); // La vue est appellée en premier, puis le layout. 
              $this->headTitle('Mon site');
              echo $this->headTitle() . PHP_EOL;
              
              $this->headLink()->appendStylesheet('/css/style.css', 'all'); 
              $this->headLink()->appendStylesheet('/css/reset.css', 'all'); 
              $this->headLink()->appendStylesheet('/css/fonts.css', 'all'); 
              echo $this->headLink(). PHP_EOL; 
              
              $this->headScript()->appendFile('/js/less-grid-4.js', 'text/javascript');
              echo $this->headScript() . PHP_EOL; 
        ?>      
     	
    </head>

    <body>
    <h1>App8.  IP FORMATION</h1>
    <nav id="topNav">
        <ul>
        	<li><a href="/home">Index</a></li>
        	<li><a href="/contact/contact">Contact</a></li>
       	</ul>
    </nav>
    <div id="page">
        <?php echo $this->layout()-> content?> 
    </div>
	    <footer>
        	<p><i>Application PHP 5</i></p>
        </footer>
    </body>
</html>

