<?php 
$this->headMeta()->appendName('Keywords', 'sfgbvdcsd, fbnfgf');
$this->headMeta()->appendName('Description', 'sdfskjhgfdssdf');
$this->headTitle('Accueil ');
$this->headLink()->appendStylesheet('/css/specific.css', 'screen');
?>

<div id="first_content">
		<div class="box">
			<div class="text_box">
				<p class="title">Lorem Ipsum</p>
				<p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et elit in risus mollis commodo nec consequat lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Curabitur et massa nec ligula volutpat sollicitudin.</p>
				<a href =""><img src="/img/button.png" alt="More" class="more" /></a>
			</div>
			<div class="text_box" >	
				<p class="video_text">" Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus tellus nunc, lobortis ac consectetur nec, suscipit at felis. Fusce sem lectus, sagittis sit amet dignissim non, varius at mi. Curabitur ornare, sem eget laoreet interdum, ipsum neque dignissim augue, vel rutrum ante tellus vel libero."</p>
				<p class="video_text">"Lobortis ac consectetur nec, suscipit at felis. Fusce sem lectus, sagittis sit amet dignissim non, varius at mi. Curabitur ornare, sem eget laoreet interdum, ipsum neque dignissim augue, vel rutrum ante tellus vel libero."</p>
				<p class="description" style="margin-left:200px;margin-top:-10px;"> - Lorem Ipsum</p>
			</div>
		</div>
		<img src="/img/hr.png" alt="" />
		<div class="box">
			<div class="text_box">
				<p class="title">Nunc consequat urna</p>
				<p class="description">Aliquam consequat aliquam enim, a porta turpis facilisis a. Nunc consequat urna tincidunt magna pretium cursus. Donec facilisis vulputate blandit. Ut sit amet sapien est. Nam vel odio justo, ac mattis ipsum.</p>
				<a href =""><img src="/img/button.png" alt="More" class="more" /></a>
			</div>
			<div class="text_box">
				<p class="title">Lobortis ac consectetur</p>
				<p class="description">Sed quis mollis eros. Proin consectetur, felis quis facilisis gravida, enim eros dapibus metus, nec adipiscing arcu magna nec magna. Curabitur lacus sapien, commodo ac eleifend quis, pretium at sapien. Praesent vitae mauris vel tortor cursus ullamcorper. In eu imperdiet felis. </p>
			</div>
		</div>
		<img src="/img/hr.png" alt="" />
		<div class="box">
			<div class="round_box_text">
				<p class="description"> Quisque orci risus, bibendum ut pharetra ac, commodo at lectus. </p>
				<p class="description">Nullam lectus sapien, pharetra eget commodo non, elementum eu mi. </p>
			</div>
			<div class="round_box">
				<a href="" class="caption" ><img src="/img/winner.png" class="round_box_image" alt="winner" />Become the best</a>
			</div>
			<div class="round_box">
				<a href="" class="caption" ><img src="/img/customer.png" class="round_box_image" alt="customer" />Support</a>
			</div>
			<div class="round_box">
				<a href="" class="caption" ><img src="/img/graph.png" class="round_box_image" alt="graph" />Statistics</a>
			</div>
		</div>
		<img src="/img/hr.png" alt="" />
			<br />
			<br />
		<div class="big_round_box">
			<p class="title">Lorem Ipsum</p>
			<p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et elit in risus mollis commodo nec consequat lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Curabitur et massa nec ligula volutpat sollicitudin. Aliquam consequat aliquam enim, a porta turpis facilisis a. Nunc consequat urna tincidunt magna pretium cursus.  </p>
		</div>
	</div>