<?php 
$this->headMeta()->appendName('Keywords', 'sdfsdfsd, fsdf');
$this->headMeta()->appendName('Description', 'sdfsdfsdfsdf');
$this->headTitle('titre de la page d\'accueil');
$this->headLink()->appendStylesheet('/css/specific.css', 'screen');
$this->headScript()->appendFile("http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js","text/javascript");

?>
<h1>Index <?php echo $this->toto ?></h1>

<p>Date du jour <?php echo $this->formatDate('2011-08-02')?></p>